// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Test 1', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Test 1', async function() {
    await driver.get("https://www.amazon.com/")
    await driver.manage().window().setRect({ width: 1552, height: 832 })
    await driver.findElement(By.css(".hm-icon")).click()
    await driver.findElement(By.css(".hmenu > li:nth-child(9) div")).click()
    await driver.findElement(By.linkText("Plugs and Outlets")).click()
    assert(await driver.findElement(By.xpath("//*[@id=\"a-page\"]/div[2]/div[2]/div[1]/div[1]/div/h1/b")).getText() == "Smart Plugs and Outlets | Smart Home")
    await driver.close()
  })
})
